// FETCH_USERSS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'
// CREATE_USERS
export const CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST'
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS'
export const CREATE_USERS_FAILED = 'CREATE_USERS_FAILED'
// READ_USERS
export const READ_USERS_REQUEST = 'READ_USERS_USERS_REQUEST'
export const READ_USERS_SUCCESS = 'READ_USERS_SUCCESS'
export const READ_USERS_FAILED = 'READ_USERS_FAILED'
// UPDATE_USERS
export const UPDATE_USERS_REQUEST = 'UPDATE_USERS_REQUEST'
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS'
export const UPDATE_USERS_FAILED = 'UPDATE_USERS_FAILED'
// DESTROY_USERS
export const DESTROY_USERS_REQUEST = 'DESTROY_USERS_REQUEST'
export const DESTROY_USERS_SUCCESS = 'DESTROY_USERS_SUCCESS'
export const DESTROY_USERS_FAILED = 'DESTROY_USERS_FAILED'
